// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nflbaphvprbowimaexom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mbGJhcGh2cHJib3dpbWFleG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjIyNzYsImV4cCI6MjA1OTkzODI3Nn0.l7Ag_HK_RP39TQ___75SCmOv-UFao9oEukh6wz4SfRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);